plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.japaneixxx.odin.notes'
    compileSdk 32

    defaultConfig {
        applicationId "com.japaneixxx.odin.notes"
        minSdk 26
        targetSdk 32
        versionCode 5
        versionName "1.4.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        viewBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation project(':shared-data')

    // Dependências de UI base (alinhadas para compileSdk 32)
    implementation 'androidx.core:core-ktx:1.8.0'
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'com.google.android.material:material:1.6.1'

    // Fragment KTX (para o AddNoteDialog e ManageTagsBottomSheet)
    implementation 'androidx.fragment:fragment-ktx:1.5.2'

    // Ciclo de vida e Coroutines
    def lifecycle_version = "2.5.1"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"

    // Delegate 'by viewModels'
    implementation "androidx.activity:activity-ktx:1.5.1"

    testImplementation 'junit:junit:4.13.2'
}